### ISSUE TITLE
Composer is not idempotent

### ISSUE THREAD

**Issue by hernandesbsousa** [augustohp/ansible-role-php#17]
This task gets marked every time even if nothing actually changed.

**Comment by augustohp** [comment]
This is actually the way `composer` works, it is idempotent.
You execute install and it resolves if it needs an installation or not, there must be something with the way [Ansible](http://ansible.com) detects idempotency with shell commands.

I am judging that [ansible](http://ansible.com) will always understand `shell` or `commands` tasks as a change operation, since all of them are are being always executed no matter what. I don't see many solutions to that other than having a way to grab facts directly from composer - which in my opinion is a round trip around the universe for very little gain.

**Comment by hernandesbsousa** [comment]
I just found out there is a Composer module, closing this and opening a new issue
