### ISSUE TITLE
Refactor composer tasks to use the composer module

### ISSUE THREAD

**Issue by hernandesbsousa** [augustohp/ansible-role-php#22]
There is a composer module: http://docs.ansible.com/composer_module.html that would properly handle most of the tasks being done via the `command` and `shell` modules.

**Comment by augustohp** [comment]
The composer usage on this role has the point of making available composer as a global command, I do not intent do manage application provisioning - since there are far [better](http://ant.apache.org/) [tools](http://capistranorb.com/) for that.

That being said:
- Do we really need that module? That would bump requirements from Ansible 1.5 to 1.6.
- Will [global](https://getcomposer.org/doc/03-cli.md#global) command work? It is the only (fair) use of composer for this role as I see it. (That would probably bump requirements to Ansible 1.8)

**Comment by augustohp** [comment]
Unnecessary since #24:
- Shell command of composer installation properly checks `changed` state.
- No greater version of Ansible required.
